---
# dependencies
- name: Install some deps
  ansible.builtin.apt:
    name:
      - bzip2
      - ca-certificates
      - curl
      - dirmngr
      - fonts-liberation
      - fonts-noto
      - fonts-noto-cjk
      - fonts-noto-mono
      - geoip-database
      - gnupg
      - gsfonts
      - inetutils-ping
      - libgnutls-dane0
      - libgts-bin
      - libpaper-utils
      - locales
      - lzop
      - nfs-common
      - nodejs
      - npm
      - python3
      - python3-babel
      - python3-chardet
      - python3-cryptography
      - python3-cups
      - python3-dateutil
      - python3-decorator
      - python3-docutils
      - python3-feedparser
      - python3-freezegun
      - python3-geoip2
      - python3-gevent
      - python3-greenlet
      - python3-html2text
      - python3-idna
      - python3-jinja2
      - python3-ldap
      - python3-libsass
      - python3-lxml
      - python3-markupsafe
      - python3-num2words
      - python3-ofxparse
      - python3-olefile
      - python3-openssl
      - python3-paramiko
      - python3-passlib
      - python3-pdfminer
      - python3-phonenumbers
      - python3-pil
      - python3-pip
      - python3-polib
      - python3-psutil
      - python3-psycopg2
      - python3-pydot
      - python3-pylibdmtx
      - python3-pyparsing
      - python3-pypdf2
      - python3-pytzdata
      - python3-qrcode
      - python3-renderpm
      - python3-reportlab
      - python3-reportlab-accel
      - python3-requests
      - python3-rjsmin
      - python3-serial
      - python3-setuptools
      - python3-stdnum
      - python3-urllib3
      - python3-usb
      - python3-vobject
      - python3-werkzeug
      - python3-xlrd
      - python3-xlsxwriter
      - python3-xlwt
      - python3-zeep
      - shared-mime-info
      - unzip
      - xz-utils
      - zip
      - zstd
    state: present
    install_recommends: false

- name: Delete EXTERNALLY-MANAGED file
  ansible.builtin.file:
    path: "/usr/lib/python3.11/EXTERNALLY-MANAGED"
    state: absent

- name: Pip addons
  ansible.builtin.pip:
    executable: pip3
    name:
      - ebaysdk
      - google-auth
    state: present

- name: Install "rtlcss" node.js package
  community.general.npm:
    name: rtlcss
    global: true
    state: present
